"""
The account's real size vocabulary — read from NetSuite, not invented here.

Why this is its own module. The attachment classifier locates a sheet's size
header row by recognising size labels in it, and that recognition used to run off
a hand-written set of letter sizes (`XS`…`4XL`). That set was wrong in a way no
test could catch, because it was wrong by *omission*: Straight Down sells
footwear and bottoms, whose sizes are numbers (`8`…`14`, `30`…`44`, `9.5`,
`10.5`) and waist-inseam pairs (`32-34`). A numerically-sized packing sheet
therefore showed no recognisable size labels, was reported as "packing list but
no per-size quantities", and the whole document went to manual entry — with the
size grid sitting in plain view two rows down.

A hand-written set cannot be the fix, only a bigger version of the same bug: the
next scale someone adds in NetSuite (kids', tall, half sizes) would be invisible
here again. So the vocabulary is **the live `customlist_psgss_product_size`
values**, cached to a snapshot file that is *generated*, never edited by hand:

    python size_vocabulary.py --refresh      # re-reads NetSuite, rewrites the snapshot
    python size_vocabulary.py --check        # reports drift without writing

The snapshot exists because classification must work offline and must not pay a
NetSuite round trip per attachment; `--check` is what keeps it honest. Drift is
reported as a warning, never silently corrected mid-run — a classification whose
vocabulary changed underneath it should be reproducible.

Both `name` and `abbreviation` are admitted as labels. In this account they are
almost always identical, but `ALL` carries abbreviation `A`, and a vendor writing
either one means the same size.
"""

from __future__ import annotations

import json
import logging
import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Iterable, Optional

from canonical import canonical

logger = logging.getLogger(__name__)

#: Generated by `--refresh`. Not hand-maintained -- see the module docstring.
SNAPSHOT_PATH = Path(__file__).with_name("netsuite_size_list.json")

#: The NetSuite custom list holding every size this account sells.
SIZE_LIST_ID = "customlist_psgss_product_size"


class SizeVocabularyUnavailable(RuntimeError):
    """No snapshot on disk and no live client to build one from."""


# ---------------------------------------------------------------------------
# Reading the live list
# ---------------------------------------------------------------------------


def fetch_live(client: Any) -> list[dict]:
    """
    Every value in `customlist_psgss_product_size`, from NetSuite.

    SuiteQL first: one call for the whole list, and it returns `name` and
    `abbreviation` together. It is gated behind `Reports > SuiteAnalytics
    Workbook`, which this role happens to have -- but that is a role setting
    someone can change, so a refusal falls back to the record API instead of
    failing. The fallback costs one call per value (46 today), which is why it is
    the fallback and not the primary.

    `isinactive` values are kept and marked rather than dropped: a size retired in
    NetSuite still appears on packing lists for orders placed before it was
    retired, and the detector's job is to recognise the label, not to police it.
    """
    config = client._require_live("fetch_live()")
    try:
        response = client._request(
            "POST",
            config.suiteql_url,
            headers={"Prefer": "transient"},
            json={
                "q": f"SELECT id, name, abbreviation, isinactive FROM {SIZE_LIST_ID} ORDER BY id"
            },
        )
        rows = response.json().get("items", [])
        return [
            {
                "id": str(row.get("id")),
                "name": _clean(row.get("name")),
                "abbreviation": _clean(row.get("abbreviation")),
                "inactive": str(row.get("isinactive", "F")).upper() in ("T", "TRUE"),
            }
            for row in rows
        ]
    except Exception as exc:  # noqa: BLE001 -- SuiteQL is a role setting, not a guarantee
        logger.warning(
            "SuiteQL read of %s failed (%s: %s); falling back to per-record reads",
            SIZE_LIST_ID,
            type(exc).__name__,
            exc,
        )

    listing = client._request(
        "GET", f"{config.record_base}/{SIZE_LIST_ID}", params={"limit": 1000}
    ).json()
    if listing.get("hasMore"):
        # Worth knowing about rather than silently truncating: the same class of
        # bug as the sublist truncation guard.
        logger.warning(
            "%s reports hasMore=True at limit=1000 -- the snapshot may be incomplete",
            SIZE_LIST_ID,
        )
    out = []
    for item in listing.get("items", []):
        record = client._request(
            "GET", f"{config.record_base}/{SIZE_LIST_ID}/{item['id']}"
        ).json()
        out.append(
            {
                "id": str(record.get("id", item["id"])),
                "name": _clean(record.get("name")),
                "abbreviation": _clean(record.get("abbreviation")),
                "inactive": bool(record.get("isInactive")),
            }
        )
    return out


def _clean(value: Any) -> str:
    return "" if value is None else str(value).strip()


# ---------------------------------------------------------------------------
# The snapshot
# ---------------------------------------------------------------------------


def refresh_snapshot(client: Any, path: Path = SNAPSHOT_PATH) -> dict:
    """Re-read NetSuite and rewrite the snapshot. Returns the written document."""
    import datetime as dt

    values = fetch_live(client)
    config = client._require_live("refresh_snapshot()")
    document = {
        "_comment": (
            "GENERATED by `python size_vocabulary.py --refresh`. Do not edit by hand -- "
            "a hand-edited entry is exactly the drift this file exists to prevent."
        ),
        "source_list": SIZE_LIST_ID,
        "account_id": config.account_id,
        "is_sandbox": config.is_sandbox,
        "fetched_at": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
        "count": len(values),
        "values": values,
    }
    path.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    load_snapshot.cache_clear()
    size_labels.cache_clear()
    _size_labels_canon.cache_clear()
    return document


@lru_cache(maxsize=1)
def load_snapshot(path: Optional[str] = None) -> dict:
    file_path = Path(path) if path else SNAPSHOT_PATH
    if not file_path.is_file():
        raise SizeVocabularyUnavailable(
            f"no size-list snapshot at {file_path}. Build one with "
            f"`python size_vocabulary.py --refresh` (needs NetSuite credentials)."
        )
    return json.loads(file_path.read_text(encoding="utf-8"))


def check_drift(client: Any, path: Path = SNAPSHOT_PATH) -> dict:
    """
    Compare the snapshot against the live list. Reports; does not rewrite.

    Returns `{"added": [...], "removed": [...], "in_sync": bool}` where `added`
    is live-but-not-snapshotted -- the direction that silently breaks detection.
    """
    live = {v["name"] for v in fetch_live(client) if v["name"]}
    stored = {v["name"] for v in load_snapshot(str(path)).get("values", []) if v["name"]}
    added = sorted(live - stored)
    removed = sorted(stored - live)
    return {"added": added, "removed": removed, "in_sync": not added and not removed}


# ---------------------------------------------------------------------------
# The vocabulary the detector uses
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def size_labels() -> frozenset[str]:
    """Every size label in the account, names and abbreviations alike."""
    values = load_snapshot().get("values", [])
    return frozenset(
        label
        for value in values
        for label in (value.get("name", ""), value.get("abbreviation", ""))
        if label
    )


@lru_cache(maxsize=1)
def _size_labels_canon() -> frozenset[str]:
    return frozenset(canonical(label) for label in size_labels())


def size_labels_canon(extra: Optional[Iterable[str]] = None) -> frozenset[str]:
    """
    The vocabulary in canonical form, which is how vendor cell text is compared.

    Same reasoning as every other vendor-text-against-our-vocabulary site in this
    project: a sheet writing a full-width `２Ｘ` or a double-spaced `One  Size`
    must still be recognised. `extra` is for tests that need a label the account
    does not have; production passes nothing.
    """
    base = _size_labels_canon()
    if not extra:
        return base
    return base | frozenset(canonical(label) for label in extra)


#: A cell that is a bare number, with or without a trailing `.0` from a float
#: cell. Anchored so `8-14#` and `Qty 8` are not numbers.
_BARE_NUMBER = re.compile(r"^[0-9]+(?:\.[0-9]+)?$")

#: A waist-inseam pair as NetSuite spells it: `32-34`. Matched as a whole label
#: against the list rather than parsed, because only the list knows which pairs
#: exist -- `32-34` is a size, `2-3` (a carton range on Tainan's sheet) is not.
_NUMBER_PAIR = re.compile(r"^[0-9]+\s*-\s*[0-9]+$")


def numeric_label(text: str) -> Optional[str]:
    """
    A bare-number cell rendered the way NetSuite spells the size, or None.

    `'8'` -> `'8'`, `30.0` -> `'30'` (**not** `'30.0'` -- the list holds `30`, and
    a float cell is how Tainan's sheet stores its waist row), `9.5` -> `'9.5'`,
    `'10.50'` -> `'10.5'`. Anything that is not a bare number returns None.
    """
    stripped = str(text or "").strip()
    if not _BARE_NUMBER.match(stripped):
        return None
    number = float(stripped)
    if number.is_integer():
        return str(int(number))
    # Trim trailing zeros so '10.50' and 10.5 both land on the list's '10.5'.
    return f"{number:.4f}".rstrip("0").rstrip(".")


if __name__ == "__main__":  # pragma: no cover -- operator tooling
    import argparse
    import sys

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--refresh", action="store_true", help="re-read NetSuite, rewrite the snapshot")
    ap.add_argument("--check", action="store_true", help="report drift without writing")
    args = ap.parse_args()

    if args.refresh or args.check:
        from netsuite_client import NetSuiteClient, NetSuiteConfig

        client = NetSuiteClient(config=NetSuiteConfig.from_env())
        client.authenticate(force=True)
        if args.refresh:
            doc = refresh_snapshot(client)
            print(f"wrote {SNAPSHOT_PATH.name}: {doc['count']} values from {doc['account_id']}")
        else:
            drift = check_drift(client)
            print(f"in sync: {drift['in_sync']}")
            if drift["added"]:
                print(f"  live but NOT in the snapshot (detection gap): {drift['added']}")
            if drift["removed"]:
                print(f"  in the snapshot but not live: {drift['removed']}")
            sys.exit(0 if drift["in_sync"] else 1)
    else:
        snapshot = load_snapshot()
        print(f"{snapshot['count']} size labels, fetched {snapshot['fetched_at']}")
        print("  " + ", ".join(sorted(size_labels())))
