"""initial schema

Everything the pipeline stores, in one migration: the intake tables, the work
item and its PO fan-out, the line-level proposals with their candidates and write
attempts, the append-only audit log, the state machine as seeded data, and two
views.

Autogenerated from `schema.py` and then completed by hand with the data migration
and the views (Alembic does not generate either). Rationale for every table and
constraint -- one section per discovered constraint -- is in
`PO-Update-Automation-Schema-Rationale.md`.

**Do not edit this file once it has been applied anywhere.** Change `schema.py`
and generate a new revision; `alembic check` reports drift between the two.

Revision ID: 0001
Revises: 
Create Date: 2026-08-26 09:41:36.004106
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from schema import CHANGE_STATE_TRANSITIONS, CHANGE_STATES, VIEWS


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('doc_type_reason', sa.String(length=1000), nullable=True),
    sa.Column('open_failure_reason', sa.String(length=500), nullable=True),
    sa.Column('banned_as_data_source', sa.Boolean(), nullable=False),
    sa.Column('stored_uri', sa.String(length=1000), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("doc_type IN ('PACKING_LIST','COMMERCIAL_INVOICE','SHIPPING_ADVICE','SHIPPING_SCHEDULE','PAYMENT_REQUEST','INSPECTION_REPORT','OTHER','UNREADABLE')", name=op.f('ck_attachments_doc_type')),
    sa.PrimaryKeyConstraint('content_sha256', name=op.f('pk_attachments'))
    )
    op.create_table('change_states',
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('state', name=op.f('pk_change_states'))
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('graph_message_id', sa.String(length=512), nullable=False),
    sa.Column('internet_message_id', sa.String(length=512), nullable=True),
    sa.Column('mailbox', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('forwarded_by', sa.String(length=320), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('graph_message_id', name='uq_messages_graph_message_id')
    )
    op.create_table('change_state_transitions',
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('actor_kind', sa.String(length=8), nullable=False),
    sa.CheckConstraint("actor_kind IN ('HUMAN','SYSTEM')", name=op.f('ck_change_state_transitions_actor_kind')),
    sa.ForeignKeyConstraint(['from_state'], ['change_states.state'], name=op.f('fk_change_state_transitions_from_state')),
    sa.ForeignKeyConstraint(['to_state'], ['change_states.state'], name=op.f('fk_change_state_transitions_to_state')),
    sa.PrimaryKeyConstraint('from_state', 'to_state', 'trigger', name=op.f('pk_change_state_transitions'))
    )
    op.create_table('message_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['content_sha256'], ['attachments.content_sha256'], name=op.f('fk_message_attachments_content_sha256')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_attachments_message_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_attachments')),
    sa.UniqueConstraint('message_id', 'content_sha256', name='uq_message_attachments_pair')
    )
    op.create_table('shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('primary_attachment_sha', sa.String(length=64), nullable=True),
    sa.Column('source_set_hash', sa.String(length=64), nullable=True),
    sa.Column('superseded_by_shipment_id', sa.String(length=36), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('vendor_etd', sa.String(length=40), nullable=True),
    sa.Column('vendor_eta', sa.String(length=40), nullable=True),
    sa.Column('parser', sa.String(length=64), nullable=True),
    sa.Column('extractor_model', sa.String(length=64), nullable=True),
    sa.Column('extractor_prompt_version', sa.String(length=64), nullable=True),
    sa.Column('doc_needs_review', sa.Boolean(), nullable=False),
    sa.Column('needs_manual_entry', sa.Boolean(), nullable=False),
    sa.Column('parse_warnings_json', sa.Text(), nullable=True),
    sa.Column('parse_notes_json', sa.Text(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('unit_total', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(origin = 'VENDOR_EMAIL' AND message_id IS NOT NULL) OR (origin = 'PAULA_DIRECTED' AND message_id IS NULL  AND primary_attachment_sha IS NULL)", name=op.f('ck_shipments_provenance')),
    sa.CheckConstraint("origin IN ('VENDOR_EMAIL','PAULA_DIRECTED')", name=op.f('ck_shipments_origin')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_shipments_message_id')),
    sa.ForeignKeyConstraint(['primary_attachment_sha'], ['attachments.content_sha256'], name=op.f('fk_shipments_primary_attachment_sha')),
    sa.ForeignKeyConstraint(['superseded_by_shipment_id'], ['shipments.id'], name=op.f('fk_shipments_superseded_by_shipment_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments'))
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index('ix_shipments_source_set_hash', ['source_set_hash'], unique=False)
        batch_op.create_index('ux_shipments_primary_attachment', ['primary_attachment_sha'], unique=True, sqlite_where=sa.text('primary_attachment_sha IS NOT NULL AND superseded_by_shipment_id IS NULL'), mssql_where='primary_attachment_sha IS NOT NULL AND superseded_by_shipment_id IS NULL')

    op.create_table('shipment_pos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('po_number_printed', sa.String(length=120), nullable=False),
    sa.Column('po_number_key', sa.String(length=40), nullable=False),
    sa.Column('ns_tranid', sa.String(length=40), nullable=True),
    sa.Column('ns_internal_id', sa.String(length=40), nullable=True),
    sa.Column('resolution_status', sa.String(length=16), nullable=False),
    sa.Column('resolution_strategy', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resolution_status IN ('UNRESOLVED','RESOLVED','NOT_FOUND','AMBIGUOUS')", name=op.f('ck_shipment_pos_resolution_status')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipment_pos_shipment_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_pos')),
    sa.UniqueConstraint('shipment_id', 'po_number_key', name='uq_shipment_pos_key')
    )
    op.create_table('shipment_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=500), nullable=True),
    sa.Column('agreement_json', sa.Text(), nullable=True),
    sa.CheckConstraint("role IN ('PRIMARY','CROSS_CHECK','EXCLUDED')", name=op.f('ck_shipment_sources_role')),
    sa.ForeignKeyConstraint(['content_sha256'], ['attachments.content_sha256'], name=op.f('fk_shipment_sources_content_sha256')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipment_sources_shipment_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_sources')),
    sa.UniqueConstraint('shipment_id', 'content_sha256', name='uq_shipment_sources_pair')
    )
    op.create_table('proposed_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('shipment_po_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('key_style', sa.String(length=64), nullable=False),
    sa.Column('key_color', sa.String(length=64), nullable=False),
    sa.Column('key_size', sa.String(length=32), nullable=False),
    sa.Column('src_style_text', sa.String(length=200), nullable=False),
    sa.Column('src_color_text', sa.String(length=200), nullable=False),
    sa.Column('src_size_text', sa.String(length=100), nullable=False),
    sa.Column('src_quantity_text', sa.String(length=100), nullable=True),
    sa.Column('source_hint', sa.String(length=120), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('ns_line_id', sa.String(length=40), nullable=True),
    sa.Column('ns_item_internal_id', sa.String(length=40), nullable=True),
    sa.Column('current_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('current_quantity_received', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('proposed_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('current_expected_receipt_date', sa.Date(), nullable=True),
    sa.Column('current_updated_receipt_date', sa.Date(), nullable=True),
    sa.Column('current_override_flag', sa.Boolean(), nullable=True),
    sa.Column('ns_line_is_open', sa.Boolean(), nullable=True),
    sa.Column('ns_line_closed', sa.Boolean(), nullable=True),
    sa.Column('extraction_confidence', sa.String(length=8), nullable=False),
    sa.Column('extraction_note', sa.String(length=1000), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('attention_reason', sa.Text(), nullable=True),
    sa.Column('human_verdict', sa.String(length=20), nullable=True),
    sa.Column('human_verdict_note', sa.String(length=1000), nullable=True),
    sa.Column('verdict_by', sa.String(length=320), nullable=True),
    sa.Column('verdict_at', sa.DateTime(), nullable=True),
    sa.Column('approved_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantity_approved_by', sa.String(length=320), nullable=True),
    sa.Column('quantity_approved_at', sa.DateTime(), nullable=True),
    sa.Column('quantity_write_status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_receipt_date', sa.Date(), nullable=True),
    sa.Column('date_approved_by', sa.String(length=320), nullable=True),
    sa.Column('date_approved_at', sa.DateTime(), nullable=True),
    sa.Column('date_write_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("date_write_status = 'NONE' OR confirmed_receipt_date IS NOT NULL", name=op.f('ck_proposed_changes_date_scope_needs_date')),
    sa.CheckConstraint("date_write_status IN ('NONE','APPROVED','WRITTEN','FAILED')", name=op.f('ck_proposed_changes_date_write_status')),
    sa.CheckConstraint("extraction_confidence IN ('high','medium','low')", name=op.f('ck_proposed_changes_extraction_confidence')),
    sa.CheckConstraint("human_verdict IS NULL OR human_verdict IN ('ACCEPTED','CORRECTED','REJECTED','CANDIDATE_PICKED')", name=op.f('ck_proposed_changes_human_verdict')),
    sa.CheckConstraint("quantity_write_status = 'NONE' OR approved_quantity IS NOT NULL", name=op.f('ck_proposed_changes_quantity_scope_needs_quantity')),
    sa.CheckConstraint("quantity_write_status IN ('NONE','APPROVED','WRITTEN','FAILED')", name=op.f('ck_proposed_changes_quantity_write_status')),
    sa.CheckConstraint("state NOT IN ('APPROVED','WRITTEN','WRITE_FAILED') OR ns_line_id IS NOT NULL", name=op.f('ck_proposed_changes_target_required')),
    sa.CheckConstraint('confirmed_receipt_date IS NULL OR date_approved_by IS NOT NULL', name=op.f('ck_proposed_changes_date_needs_human')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_proposed_changes_shipment_id')),
    sa.ForeignKeyConstraint(['shipment_po_id'], ['shipment_pos.id'], name=op.f('fk_proposed_changes_shipment_po_id')),
    sa.ForeignKeyConstraint(['source_sha256'], ['attachments.content_sha256'], name=op.f('fk_proposed_changes_source_sha256')),
    sa.ForeignKeyConstraint(['state'], ['change_states.state'], name=op.f('fk_proposed_changes_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposed_changes'))
    )
    with op.batch_alter_table('proposed_changes', schema=None) as batch_op:
        batch_op.create_index('ix_proposed_changes_shipment_id', ['shipment_id'], unique=False)
        batch_op.create_index('ix_proposed_changes_state', ['state'], unique=False)
        batch_op.create_index('ux_proposed_changes_canonical_key', ['shipment_po_id', 'key_style', 'key_color', 'key_size'], unique=True, sqlite_where=sa.text("key_size <> ''"), mssql_where="key_size <> ''")

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('workflow', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('actor_kind', sa.String(length=8), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('change_id', sa.String(length=36), nullable=True),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.CheckConstraint("actor_kind IN ('HUMAN','SYSTEM')", name=op.f('ck_audit_log_actor_kind')),
    sa.CheckConstraint("workflow IN ('PACKING_SLIP','PAULA_DIRECTED')", name=op.f('ck_audit_log_workflow')),
    sa.ForeignKeyConstraint(['change_id'], ['proposed_changes.id'], name=op.f('fk_audit_log_change_id')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_audit_log_message_id')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_audit_log_shipment_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_change_id_occurred_at', ['change_id', 'occurred_at'], unique=False)

    op.create_table('change_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('ns_line_id', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantity_billed', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('expected_receipt_date', sa.Date(), nullable=True),
    sa.Column('updated_receipt_date', sa.Date(), nullable=True),
    sa.Column('override_expected_receipt', sa.Boolean(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['proposed_changes.id'], name=op.f('fk_change_candidates_change_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_candidates')),
    sa.UniqueConstraint('change_id', 'ns_line_id', name='uq_change_candidates_line')
    )
    with op.batch_alter_table('change_candidates', schema=None) as batch_op:
        batch_op.create_index('ux_change_candidates_one_selected', ['change_id'], unique=True, sqlite_where=sa.text('selected = 1'), mssql_where='selected = 1')

    op.create_table('write_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('ns_internal_id', sa.String(length=40), nullable=False),
    sa.Column('ns_line_id', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_kind', sa.String(length=24), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("error_kind IS NULL OR error_kind IN ('PERMISSION','TRANSIENT','CONFLICT','LINE_CLOSED','VALIDATION','OTHER')", name=op.f('ck_write_attempts_error_kind')),
    sa.CheckConstraint("outcome IN ('SUCCESS','FAILED')", name=op.f('ck_write_attempts_outcome')),
    sa.CheckConstraint("scope IN ('QUANTITY','DATE')", name=op.f('ck_write_attempts_scope')),
    sa.ForeignKeyConstraint(['change_id'], ['proposed_changes.id'], name=op.f('fk_write_attempts_change_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_write_attempts')),
    sa.UniqueConstraint('change_id', 'scope', 'attempt_no', name='uq_write_attempts_attempt')
    )
    # ### end Alembic commands ###

    # -- data migration: the state machine ships WITH the schema ---------------
    # Seeded here rather than at application startup so the legal transitions
    # cannot disagree with the code that reads them, and so a fresh database is
    # immediately usable. `proposed_changes.state` has a foreign key to
    # `change_states`, which makes a typo'd status an integrity error instead of a
    # row nobody notices.
    bind = op.get_bind()
    states = sa.table(
        "change_states",
        sa.column("state", sa.String),
        sa.column("is_terminal", sa.Boolean),
        sa.column("description", sa.String),
    )
    op.bulk_insert(
        states,
        [
            {"state": state, "is_terminal": is_terminal, "description": description}
            for state, is_terminal, description in CHANGE_STATES
        ],
    )
    transitions = sa.table(
        "change_state_transitions",
        sa.column("from_state", sa.String),
        sa.column("to_state", sa.String),
        sa.column("trigger", sa.String),
        sa.column("actor_kind", sa.String),
    )
    op.bulk_insert(
        transitions,
        [
            {
                "from_state": from_state,
                "to_state": to_state,
                "trigger": trigger,
                "actor_kind": actor_kind,
            }
            for from_state, to_state, trigger, actor_kind in CHANGE_STATE_TRANSITIONS
        ],
    )

    # -- views: ANSI-only SQL, one statement per engine ------------------------
    for _name, ddl in VIEWS:
        bind.execute(sa.text(ddl))


def downgrade() -> None:
    # Views first: they depend on the tables. The seeded rows go with their
    # tables, so there is nothing to delete explicitly.
    bind = op.get_bind()
    for name, _ddl in reversed(VIEWS):
        bind.execute(sa.text(f"DROP VIEW IF EXISTS {name}"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('write_attempts')
    with op.batch_alter_table('change_candidates', schema=None) as batch_op:
        batch_op.drop_index('ux_change_candidates_one_selected', sqlite_where=sa.text('selected = 1'), mssql_where='selected = 1')

    op.drop_table('change_candidates')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_change_id_occurred_at')

    op.drop_table('audit_log')
    with op.batch_alter_table('proposed_changes', schema=None) as batch_op:
        batch_op.drop_index('ux_proposed_changes_canonical_key', sqlite_where=sa.text("key_size <> ''"), mssql_where="key_size <> ''")
        batch_op.drop_index('ix_proposed_changes_state')
        batch_op.drop_index('ix_proposed_changes_shipment_id')

    op.drop_table('proposed_changes')
    op.drop_table('shipment_sources')
    op.drop_table('shipment_pos')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index('ux_shipments_primary_attachment', sqlite_where=sa.text('primary_attachment_sha IS NOT NULL AND superseded_by_shipment_id IS NULL'), mssql_where='primary_attachment_sha IS NOT NULL AND superseded_by_shipment_id IS NULL')
        batch_op.drop_index('ix_shipments_source_set_hash')

    op.drop_table('shipments')
    op.drop_table('message_attachments')
    op.drop_table('change_state_transitions')
    op.drop_table('messages')
    op.drop_table('change_states')
    op.drop_table('attachments')
    # ### end Alembic commands ###
